### ISSUE TITLE
Missing documentation on setting host and installing dependencies

### ISSUE THREAD

**Issue by chaudhariatul** [amd/RyzenAI-cloud-to-client-demo#4]
Request to add links and references to the following:

1. Ryzen AI SDK Documentation
2. Setting up OS
2.1. Installing drivers
3. List of supported OS
3.1. Roadmap for other OS support (Ubuntu, RedHat)
4. Examples for working with live feeds

**Comment by andyluo7** [comment]
@chaudhariatul, they will be discussed on the roadmap.
