### ISSUE TITLE
Maybe a smaller example?

### ISSUE THREAD

**Issue by emerth** [amd/RyzenAI-cloud-to-client-demo#6]
I have a 7940HS based notebook. Want to mess with the AI processor, don't want to deal with clouds and web toolkits,  accounts on Microsoft. Python is OK, but I understood there to be a C++ binding too?

Can we have a simple local Hello World style example to let people get into this without all the massive web/cloud infrastructure?

(edit)

Something like standing up a pretrained model and running inference on it, or training maybe Googlenet or similar on the AI processor.

I understand AMD wants to show how the AI processor can be a fallback from a cloud based system. There is also potential in using the processor in a strictly local mode...

**Comment by quentonh** [comment]
@emerth We intend on releasing our first formal release of the Ryzen AI Developer Guide very soon.  It should better align with the type of experience and collateral that you are looking for.  This URL will be the primarly landing page for that release.  I would anticipate this to be public in the next two weeks:   https://ryzenai.docs.amd.com/en/latest/

**Comment by emerth** [comment]
OK, that's great, thank!
